# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ps_pl_hdmi.xdc

# Block Designs: bd/ps_pl_hdmi/ps_pl_hdmi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi || ORIG_REF_NAME==ps_pl_hdmi}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_processing_system7_0_0/ps_pl_hdmi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_processing_system7_0_0 || ORIG_REF_NAME==ps_pl_hdmi_processing_system7_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_vdma_0_0/ps_pl_hdmi_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_vdma_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_vdma_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_mem_intercon_0/ps_pl_hdmi_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_mem_intercon_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_mem_intercon_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_140M_0/ps_pl_hdmi_rst_processing_system7_0_140M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rst_processing_system7_0_140M_0 || ORIG_REF_NAME==ps_pl_hdmi_rst_processing_system7_0_140M_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_processing_system7_0_axi_periph_0/ps_pl_hdmi_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==ps_pl_hdmi_processing_system7_0_axi_periph_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_100M_0/ps_pl_hdmi_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ps_pl_hdmi_rst_processing_system7_0_100M_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axis_subset_converter_0_0/ps_pl_hdmi_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axis_subset_converter_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axis_subset_converter_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_xlconstant_0_0/ps_pl_hdmi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_xlconstant_0_0 || ORIG_REF_NAME==ps_pl_hdmi_xlconstant_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_axi4s_vid_out_0_0/ps_pl_hdmi_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ps_pl_hdmi_v_axi4s_vid_out_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_tc_0_0/ps_pl_hdmi_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_v_tc_0_0 || ORIG_REF_NAME==ps_pl_hdmi_v_tc_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_xbar_0/ps_pl_hdmi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_xbar_0 || ORIG_REF_NAME==ps_pl_hdmi_xbar_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rgb2dvi_0_0/ps_pl_hdmi_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==ps_pl_hdmi_rgb2dvi_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_dynclk_0_0/ps_pl_hdmi_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_dynclk_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_dynclk_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_0_0/ps_pl_hdmi_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_gpio_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_gpio_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_xlconstant_1_0/ps_pl_hdmi_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_xlconstant_1_0 || ORIG_REF_NAME==ps_pl_hdmi_xlconstant_1_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_xlconcat_0_0/ps_pl_hdmi_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_xlconcat_0_0 || ORIG_REF_NAME==ps_pl_hdmi_xlconcat_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_1_0/ps_pl_hdmi_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_gpio_1_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_gpio_1_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_0_0/ps_pl_hdmi_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_uartlite_0_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_1_0/ps_pl_hdmi_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_uartlite_1_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_uartlite_1_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_auto_pc_0/ps_pl_hdmi_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_auto_pc_0 || ORIG_REF_NAME==ps_pl_hdmi_auto_pc_0}]

# IP: bd/ps_pl_hdmi/ip/ps_pl_hdmi_auto_pc_1/ps_pl_hdmi_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_auto_pc_1 || ORIG_REF_NAME==ps_pl_hdmi_auto_pc_1}]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_processing_system7_0_0/ps_pl_hdmi_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_processing_system7_0_0 || ORIG_REF_NAME==ps_pl_hdmi_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_vdma_0_0/ps_pl_hdmi_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_vdma_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_vdma_0_0/ps_pl_hdmi_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_vdma_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_vdma_0_0/ps_pl_hdmi_axi_vdma_0_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_140M_0/ps_pl_hdmi_rst_processing_system7_0_140M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rst_processing_system7_0_140M_0 || ORIG_REF_NAME==ps_pl_hdmi_rst_processing_system7_0_140M_0}]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_140M_0/ps_pl_hdmi_rst_processing_system7_0_140M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rst_processing_system7_0_140M_0 || ORIG_REF_NAME==ps_pl_hdmi_rst_processing_system7_0_140M_0}]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_140M_0/ps_pl_hdmi_rst_processing_system7_0_140M_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_100M_0/ps_pl_hdmi_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ps_pl_hdmi_rst_processing_system7_0_100M_0}]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_100M_0/ps_pl_hdmi_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==ps_pl_hdmi_rst_processing_system7_0_100M_0}]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_100M_0/ps_pl_hdmi_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axis_subset_converter_0_0/ps_pl_hdmi_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_axi4s_vid_out_0_0/ps_pl_hdmi_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ps_pl_hdmi_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_axi4s_vid_out_0_0/ps_pl_hdmi_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_tc_0_0/ps_pl_hdmi_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_v_tc_0_0 || ORIG_REF_NAME==ps_pl_hdmi_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_tc_0_0/ps_pl_hdmi_v_tc_0_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_xbar_0/ps_pl_hdmi_xbar_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==ps_pl_hdmi_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==ps_pl_hdmi_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_0_0/ps_pl_hdmi_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_gpio_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_0_0/ps_pl_hdmi_axi_gpio_0_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_0_0/ps_pl_hdmi_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_gpio_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_1_0/ps_pl_hdmi_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_gpio_1_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_1_0/ps_pl_hdmi_axi_gpio_1_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_1_0/ps_pl_hdmi_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_gpio_1_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_0_0/ps_pl_hdmi_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_0_0/ps_pl_hdmi_axi_uartlite_0_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_0_0/ps_pl_hdmi_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_1_0/ps_pl_hdmi_axi_uartlite_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_uartlite_1_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_uartlite_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_1_0/ps_pl_hdmi_axi_uartlite_1_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_1_0/ps_pl_hdmi_axi_uartlite_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ps_pl_hdmi_axi_uartlite_1_0 || ORIG_REF_NAME==ps_pl_hdmi_axi_uartlite_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_auto_pc_0/ps_pl_hdmi_auto_pc_0_ooc.xdc

# XDC: bd/ps_pl_hdmi/ip/ps_pl_hdmi_auto_pc_1/ps_pl_hdmi_auto_pc_1_ooc.xdc

# XDC: bd/ps_pl_hdmi/ps_pl_hdmi_ooc.xdc
