# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.cache/wt [current_project]
set_property parent.project_path /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/adt/robot_ros/MicroZus01/Demo/X_demo/ps_pl_hdmi_out/repo [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ps_pl_hdmi.bd
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_processing_system7_0_0/ps_pl_hdmi_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_vdma_0_0/ps_pl_hdmi_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_vdma_0_0/ps_pl_hdmi_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_vdma_0_0/ps_pl_hdmi_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_140M_0/ps_pl_hdmi_rst_processing_system7_0_140M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_140M_0/ps_pl_hdmi_rst_processing_system7_0_140M_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_140M_0/ps_pl_hdmi_rst_processing_system7_0_140M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_100M_0/ps_pl_hdmi_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_100M_0/ps_pl_hdmi_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rst_processing_system7_0_100M_0/ps_pl_hdmi_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axis_subset_converter_0_0/ps_pl_hdmi_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_axi4s_vid_out_0_0/ps_pl_hdmi_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_axi4s_vid_out_0_0/ps_pl_hdmi_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_tc_0_0/ps_pl_hdmi_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_v_tc_0_0/ps_pl_hdmi_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_xbar_0/ps_pl_hdmi_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_0_0/ps_pl_hdmi_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_0_0/ps_pl_hdmi_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_0_0/ps_pl_hdmi_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_1_0/ps_pl_hdmi_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_1_0/ps_pl_hdmi_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_gpio_1_0/ps_pl_hdmi_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_0_0/ps_pl_hdmi_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_0_0/ps_pl_hdmi_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_0_0/ps_pl_hdmi_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_1_0/ps_pl_hdmi_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_1_0/ps_pl_hdmi_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_axi_uartlite_1_0/ps_pl_hdmi_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_auto_pc_0/ps_pl_hdmi_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ip/ps_pl_hdmi_auto_pc_1/ps_pl_hdmi_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ps_pl_hdmi_ooc.xdc]
set_property is_locked true [get_files /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/ps_pl_hdmi.bd]

read_verilog -library xil_defaultlib /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/sources_1/bd/ps_pl_hdmi/hdl/ps_pl_hdmi_wrapper.v
read_xdc /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/constrs_1/new/ps_pl_hdmi.xdc
set_property used_in_implementation false [get_files /home/adt/robot_ros/git/vivado_project/all/X_Ubuntu.srcs/constrs_1/new/ps_pl_hdmi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ps_pl_hdmi_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef ps_pl_hdmi_wrapper.dcp
catch { report_utilization -file ps_pl_hdmi_wrapper_utilization_synth.rpt -pb ps_pl_hdmi_wrapper_utilization_synth.pb }
