set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_hpd_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HDMI_OEN[0]}]
set_property PACKAGE_PIN E18 [get_ports {hdmi_hpd_tri_i[0]}]
set_property PACKAGE_PIN F17 [get_ports {HDMI_OEN[0]}]
set_property PACKAGE_PIN H16 [get_ports TMDS_clk_p]
set_property PACKAGE_PIN D19 [get_ports {TMDS_data_p[0]}]
set_property PACKAGE_PIN C20 [get_ports {TMDS_data_p[1]}]
set_property PACKAGE_PIN B19 [get_ports {TMDS_data_p[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led4_tri_o[0]}]
set_property PACKAGE_PIN M15 [get_ports {pl_led4_tri_o[0]}]
set_property PACKAGE_PIN G14 [get_ports {pl_led4_tri_o[1]}]
set_property PACKAGE_PIN M17 [get_ports {pl_led4_tri_o[2]}]
set_property PACKAGE_PIN G15 [get_ports {pl_led4_tri_o[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports uart_lidar_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_lidar_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_driver_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_driver_txd]
set_property PACKAGE_PIN R19 [get_ports uart_lidar_rxd]
set_property PACKAGE_PIN T19 [get_ports uart_lidar_txd]
set_property PACKAGE_PIN W15 [get_ports uart_driver_rxd]
set_property PACKAGE_PIN V15 [get_ports uart_driver_txd]

